
ALTER TABLE ANIMAL ADD FOREIGN KEY (code_user) REFERENCES USER (code_user);
ALTER TABLE APPARTIENT ADD FOREIGN KEY (code_role) REFERENCES ROLE (code_role);
ALTER TABLE APPARTIENT ADD FOREIGN KEY (code_permission) REFERENCES PERMISSION (code_permission);
ALTER TABLE BOOKING ADD FOREIGN KEY (code_user_1) REFERENCES USER (code_user);
ALTER TABLE BOOKING ADD FOREIGN KEY (code_user) REFERENCES USER (code_user);
ALTER TABLE DETIENT ADD FOREIGN KEY (code_role) REFERENCES ROLE (code_role);
ALTER TABLE DETIENT ADD FOREIGN KEY (code_user) REFERENCES USER (code_user);
ALTER TABLE ETABLIR ADD FOREIGN KEY (code_user) REFERENCES USER (code_user);
ALTER TABLE ETABLIR ADD FOREIGN KEY (code_disponibility) REFERENCES DISPONIBILITY (code_disponibility);
ALTER TABLE IMAGE ADD FOREIGN KEY (code_user) REFERENCES USER (code_user);
ALTER TABLE MESSAGE ADD FOREIGN KEY (code_user_1) REFERENCES USER (code_user);
ALTER TABLE MESSAGE ADD FOREIGN KEY (code_user) REFERENCES USER (code_user);
ALTER TABLE MESSAGE_ADMIN ADD FOREIGN KEY (code_user) REFERENCES USER (code_user);
ALTER TABLE TESTIMONIAL ADD FOREIGN KEY (code_user) REFERENCES USER (code_user);